# Regresión Lineal - Parte II

In [5]:
import pandas as pd

data = pd.read_csv("datasets/winequality-red.csv", sep=";")

data.head(10)

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [6]:
data.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [10]:
import numpy as np

X = np.array([
    data["fixed acidity"],
    data["volatile acidity"],
    data["citric acid"],
]).T

X

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]])

In [29]:
X = pd.DataFrame({
    # "x1": data["fixed acidity"],
    "x2": data["volatile acidity"],
    "x3": data["citric acid"],
    # "x4": data["residual sugar"],
    "x5": data["chlorides"],
    # "x6": data["free sulfur dioxide"],
    # "x7": data["total sulfur dioxide"],
    "x8": data["density"],
    "x9": data["pH"],
    "x10": data["sulphates"],
    "x11": data["alcohol"],
})

X.head()

x2    x3     x5      x8    x9   x10  x11
0  0.70  0.00  0.076  0.9978  3.51  0.56  9.4
1  0.88  0.00  0.098  0.9968  3.20  0.68  9.8
2  0.76  0.04  0.092  0.9970  3.26  0.65  9.8
3  0.28  0.56  0.075  0.9980  3.16  0.58  9.8
4  0.70  0.00  0.076  0.9978  3.51  0.56  9.4

In [14]:
y = data["quality"]

y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

## Regresión Ridge

In [42]:
# import tal as tal
# from tal import cual

from sklearn.linear_model import Ridge

reg = Ridge()

reg.fit(X, y)

reg.score(X, y)

0.3488831070969449

In [31]:
reg.coef_

array([-1.16746669, -0.2153817 , -1.75042692,  0.3037849 , -0.52803459,
        0.85338099,  0.31166683])

## Regresión Lasso

In [43]:
from sklearn.linear_model import Lasso

reg = Lasso()

reg.fit(X, y)

reg.score(X, y)

0.0

In [44]:
reg.coef_

array([-0.,  0., -0., -0., -0.,  0.,  0.])

## Regresión Elestic-Net

In [50]:
from sklearn.linear_model import ElasticNet

reg = ElasticNet(alpha=0.1, l1_ratio=0.9) # l1_ratio 1-Lasso, 0-Ridge

reg.fit(X, y)

reg.score(X, y)

0.2150944411686152